[env:pro16MHzatmega328]
platform = atmelavr
board = pro16MHzatmega328
framework = arduino
monitor_speed = 115200
lib_deps =
    fastled/FastLED@^3.9.15
build_flags =
    -std=gnu++17
    -Wall
    -Wextra
    -Wpedantic
