FRAME_INTERVAL_MS = 20
HDD_UPDATE_MS = 10
HDD_EDGE_BOOST = 20
HDD_ACTIVE_RISE = 3
HDD_INACTIVE_DECAY = 2
HDD_MAX = 128
POWER_HOLD_FORCED_MS = 4000
STARTING_TIMEOUT_MS = 30000
SHUTDOWN_WARNING_TIMEOUT_MS = 120000
STARTUP_DURATION_MS = 2200
SHUTDOWN_DURATION_MS = 1800
RESET_DURATION_MS = 900
SHORT_POWER_LED_OFF_IGNORE_MS = 3500
POWER_LED_BLINK_MIN_HALF_PERIOD_MS = 150
POWER_LED_BLINK_MAX_HALF_PERIOD_MS = 3000
POWER_LED_BLINK_STALE_MS = 3500
POWER_LED_BLINK_EDGES_REQUIRED = 4

CPP_NAMES = {
    "FRAME_INTERVAL_MS": "FrameIntervalMs",
    "HDD_UPDATE_MS": "HddUpdateMs",
    "HDD_EDGE_BOOST": "HddEdgeBoost",
    "HDD_ACTIVE_RISE": "HddActiveRise",
    "HDD_INACTIVE_DECAY": "HddInactiveDecay",
    "HDD_MAX": "HddMax",
    "POWER_HOLD_FORCED_MS": "PowerHoldForcedMs",
    "STARTING_TIMEOUT_MS": "StartingTimeoutMs",
    "SHUTDOWN_WARNING_TIMEOUT_MS": "ShutdownWarningTimeoutMs",
    "STARTUP_DURATION_MS": "StartupDurationMs",
    "SHUTDOWN_DURATION_MS": "ShutdownDurationMs",
    "RESET_DURATION_MS": "ResetDurationMs",
    "SHORT_POWER_LED_OFF_IGNORE_MS": "ShortPowerLedOffIgnoreMs",
    "POWER_LED_BLINK_MIN_HALF_PERIOD_MS": "PowerLedBlinkMinHalfPeriodMs",
    "POWER_LED_BLINK_MAX_HALF_PERIOD_MS": "PowerLedBlinkMaxHalfPeriodMs",
    "POWER_LED_BLINK_STALE_MS": "PowerLedBlinkStaleMs",
    "POWER_LED_BLINK_EDGES_REQUIRED": "PowerLedBlinkEdgesRequired",
}
